info:
  contact: {}
paths:
  /coins:
    get:
      consumes:
      - application/json
      description: Get coins for user by token
      parameters:
      - description: username
        in: header
        name: username
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get coins for user
      tags:
      - Coins
swagger: "2.0"
